### ISSUE TITLE
Fix reference links

### ISSUE THREAD

**Issue by t-kalinowski** [edgararuiz/ecodown#15]
Currently, the reference pages created by ecodown result in incorrect links on the rendered quarto page.

If the `_quarto.yml` has: 
```
website:
  repo-actions: [edit]
```
Then the "Edit this page" link on each reference page points to the auto-generated markdown file, which is not where PR's should go. The link should ideally point to the roxygen block in the appropriate package R script.

**Comment by edgararuiz** [comment]
Fixed with #19

**Comment by edgararuiz** [comment]
With a template based reference page, we can now add custom content that uses the given Rd's metadata. The buttons will be created using a concatenated URL at the time the Rd-to-qmd conversion occurs: https://github.com/rstudio/tensorflow.rstudio.com/blob/891e94d8f5dbe0b5c4bb1b14aa1e680f21ff510b/reference/assets/_reference.qmd#L6-L8
